### ISSUE TITLE
Create a one-pager evaluation plan for semantic search

### ISSUE THREAD

**Issue by xinli-cai** [Canadian-Geospatial-Platform/semantic-search-model-evaluation#1]
Create a  one-pager comparing sentence-embedding models for semantic search, which including 

1.Semantic Search Models Comparison. 
Selecting three models from the following two popular framwork. Comparing factors could be sutiability for geospatial data, model sizes, and ease of deployment on AWS. Models 

Option 1: Sentence-transformer (or three models of your choice from https://www.sbert.net/docs/pretrained_models.html) 
- bert-base-nli-mean-tokens
- distilbert-base-nli-mean-tokens
- paraphrase-MiniLM-L6-v2

Option 2: HuggingFace Transformer BERT Models (or three models of your choice) 
- BERT base
- RoBERTa
- DistilBERT

2.Evaluation Method:
Discussing possible evaluation methods for model comparisons, considering factors include relevance and coherence.

**Comment by sajjadGG** [comment]
Sent the onepager in the slack for review
